Repository StegSchreck/RatS, pull requests merged in 2020-10, with the labels that each got.

#130 IMDb get user id from user profile - refs #119
  RatS/imdb/imdb_ratings_parser.py
Labels: hacktoberfest-accepted

#135 Add FilmtipsetInserter
  README.md
  RatS.egg-info/PKG-INFO
  RatS.egg-info/SOURCES.txt
  RatS/filmtipset/filmtipset_ratings_inserter.py
  RatS/img/RatS_Inserters_Parsers.png
  tests/assets/filmtipset/movie_details_page.html
  tests/assets/filmtipset/search_result.html
  tests/assets/filmtipset/search_result_tile.html
  tests/functional/sites/test_filmtipset_site.py
  tests/unit/filmtipset/__init__.py
  tests/unit/filmtipset/test_filmtipset_ratings_inserter.py
  transfer_ratings.py
Labels: new feature

#136 Make IMDB ID equality check independent from length of IMDB ID
  RatS/criticker/criticker_ratings_inserter.py
  RatS/filmtipset/filmtipset_ratings_inserter.py
  RatS/imdb/imdb_site.py
  RatS/listal/listal_ratings_inserter.py
  RatS/trakt/trakt_ratings_inserter.py
Labels: improvement
